version: '3'

services:

  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - auth
    ports:
      - "5432:5432"

  statefull-auth-db:
    container_name: statefull-auth-db
    image: postgres:latest
    environment:
      POSTGRES_DB: auth-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose: 
      - "5433"
    networks:
      - auth
    ports:
      - "5433:5433"
    command: -p 5433

  token-redis:
    container_name: token-redis
    image: redis:latest
    networks:
      - auth
    ports:
      - "6379:6379"

networks:
  auth:
    driver: bridge

